{ config, inputs, pkgs, ... }: let
  flake-override-inputs = "--override-input nixpkgs flake:nixpkgs";
in {
  lib = with pkgs; let
    top = extra-inputs: writeText "flake.nix.a" ''
      {
        inputs = {
          flake-utils.url = "github:numtide/flake-utils";
          nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";${extra-inputs}
        };

        outputs = inputs:
          inputs.flake-utils.lib.eachDefaultSystem (system:
            let
              pkgs = inputs.nixpkgs.legacyPackages.''${system};
            in {
              devShell = pkgs.mkShellNoCC {
                packages = with pkgs; [
    '';
    flake-template-top = top "";
    flake-template-top-with-nixche = top "\n          # nixche.url = \"github:ezjfc/nixche\"";
    flake-template-bottom = writeText "flake.nix.b" ''
                ];
              };
            }
          );
      }
    '';
    envrc-template = writeText ".envrc" ''
      # Generated by Claude Sonnet 4.6, partially edited.
      # Note: set `nix.registry.nixpkgs.flake = inputs.nixpkgs` in NixOS
              configuration reduce the space cost of using nixpkgs-unstable.

      if nix registry list | grep -q "^global flake:nixpkgs.*path:"; then
        use flake . ${flake-override-inputs}
      else
        use flake .
      fi
    '';
  in {
    inherit flake-template-top
            flake-template-top-with-nixche
            flake-template-bottom
            envrc-template;
  };


  home.packages = let
    ps = with pkgs; [
      nh
      nurl

      kccnp
      repl
      repl-update

      nil # LSP
    ];
    kccnp = pkgs.writeShellScriptBin "kccnp" ''
      nix-shell --pure --expr '(import <nixpkgs> {}).mkShellNoCC {}'
    '';
    repl = pkgs.writeShellScriptBin "repl" ''
      nix repl --expr 'import <nixpkgs> {}'
    '';
    repl-update = pkgs.writeShellScriptBin "repl-update" ''
      nix repl --expr 'import (fetchTarball
        "https://github.com/nixos/nixpkgs/tarball/nixpkgs-unstable"
      ) {}'
    '';
  in ps;

  subcommands.flake = {};
  programs.nushell.configFile.text = let
    cmds = ''
      ${flake-init}
      ${nix-develop-wrapper}
    '';
    flake-init = ''
      def "flake init" [
        --packages (-p): string = "",
        --dry,
      ] {
        mut expr = "";
        $expr += (cat ${config.lib.flake-template-top-with-nixche})
        $expr += $"            # \(extend inputs.nixche.overlay.neovim-with-lsps {\n"
        $expr += $"            # })\n"

        $expr += $"            ($packages)"
        $expr += (cat ${config.lib.flake-template-bottom})
        echo $expr                              # For piping
        print (ansi purple) $expr (ansi reset)  # For preview

        if ("flake.nix" | path exists | not $in) {
          if (not $dry) {
            $expr | save flake.nix
            git add flake.nix
          }

          print "Created and staged flake.nix"
        } else {
          panic "flake.nix already exists"
        }

        if (".envrc" | path exists | not $in) {
          if (not $dry) {
            cp ${config.lib.envrc-template} .envrc
            git add .envrc
            direnv allow
          }

          print "Created and staged .envrc"
        } # Not really cares if .envrc exists
      }
    '';
    nix-develop-wrapper = ''
      def --wrapped "nix develop" [...$rest] {
        ^nix develop ${flake-override-inputs} ...$rest
      }
    '';
  in cmds;
}
