# Network services, web browsers...

{ pkgs, ... }: {
  lazy-services = [
    "sshd"
  ];

  # Enable networking
  networking.networkmanager.enable = true;
  # Conflicts with NetworkManager:
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Install firefox.
  programs.firefox.enable = true;

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = false;
  };

  services.squid = { # Generated by ChatGPT:
    enable = true;
    configText = ''
      # http_port 3128

      # Redirect example: redirect all requests for example.com
      url_rewrite_program ${pkgs.writeShellScriptBin "url_rewrite.sh" ''
        while read url; do
          case $url in
            *"youtube.com/favicon.ico"*)
              echo "https://rule34.xxx/favicon.ico"
              ;;
            *"moodle.telt.unsw.edu.au/favicon.ico"*)
              echo "https://onlyfans.com/favicon.ico"
              ;;
            *"github.com/favicon.ico"*)
              echo "https://pornhub.com/favicon.ico"
              ;;
            *)
              # Default case: just pass the URL through
              echo "$url"
              ;;
          esac
        done
      ''}

      acl all src all
      http_access allow all

      visible_hostname myproxy
    '';
  };
}
